### ISSUE TITLE
Body min-height infinite scrolling

### ISSUE THREAD

**Issue by tomexsans** [puikinsh/gentelella#208]
I had this weird issue where the **DIV** min height is increasing infinitely.
what could be wrong i have not modified anything yet just slicing the parts and putting it on different files and including them using PHP.

**Comment by tomexsans** [comment]
![image](https://cloud.githubusercontent.com/assets/1969162/16145083/a4d9651a-34a9-11e6-8717-b91d45b6b19d.png)

**Comment by tomexsans** [comment]
found it on custom.js and disabled it? the `setContentHeight`

btw, what is its function? and what would happen if i remove it?

**Comment by christianesperar** [comment]
Can we have the the stucture of your files?

**Comment by Especially** [comment]
I'm experiencing this issue as well.

**Comment by shijistar** [comment]
The method I understand is to make sure the right content box should never too short to fill in the height of screen, especially when the content box has quite few content. I believe it must have some issue with your html structure. If you remove it your right content box would be only fill in the half of screen if the content was too few. If you can fix the issue with pure css, I think you can remove it.

**Comment by Especially** [comment]
`$RIGHT_COL.css("min-height",$(window).height());` Appears to work as it extends the page, however when using this instance, the page then resorts to its original height. And so when this is being called, it constantly is trying to resize the page back and forth, thereby generating this constantly increasing min-height. Not sure how to fix this problem. (I am also using PHP)

**Comment by DavidSili** [comment]
Was this this template by any means developed before CSS3 (and the introduction of calc(100%-...))? It solves many of the problems with dynamic height/width.
I also have the same problem with this template, and since I like the template very much, I'll try to find a cleaner solution for the problem (beside simply deleting the line from custom.js).

**Comment by marwyk** [comment]
I know this issue has been closed already. I had this exact same issue. The right_col min-height will be incremented in an infinite loop . So far I have found 2 solutions to this. The first is editing the "custom.js" file instead of having the last line in setContentHeight() function read

`$RIGHT_COL.css('min-height', contentHeight);`
you can try and replace it with 
`$RIGHT_COL.css({'min-height', "100%"});`
this stop the infinite scrolling issue for me as a start.

Then after that I noticed that if you are outputting anything before your html tags in either php or anything. The infinite scrolling  is there. I had debug info printed to the first lien of the file using `print_r()` functions in php. once i commented those out. Infinite scrolling stopped as well.

**Comment by sterlingdiazd** [comment]
I was having the same problem. After debugging for a while, I found the solution. I don't know what happen because my page was ok, and then this error appear. 

// recompute content when resizing
    $(window).smartresize(function () {
       // setContentHeight(); //JUST NEED TO COMMENT THIS AND VOILÁ!
    });
