### ISSUE TITLE
Why don't you define variables in sass file?

### ISSUE THREAD

**Issue by shijistar** [puikinsh/gentelella#224]
I'm using gentelella in my project today, it's a so good theme that provides much more than I expect. There's only one thing, why don't you define those low level style settings, such as font size, font color, link color, background of widgets, as variables in sass file? Just like what bootstrap-sass project do. You can provide default values in your project, and I can even override some of the variables according to my project's requirement, instead of adding more rules to override them. I think it will make the theme much more flexible when more and more projects use it.

**Comment by christianesperar** [comment]
Hi @shijistar1 yup you're right, the reason is this is just a complete copy of the css files (so cheat :P).
There is ongoing conversation with less vs here and decided to go on sass. There is some people who are willing to fully convert it to sass but I think they forgot it already. Hahaha. I'm too busy right now on some projects so it's not possible for me to do this as of the moment. Maybe you're interested? 

Here is the conversation: https://github.com/puikinsh/gentelella/issues/142

**Comment by shijistar** [comment]
No seems he did not forget. The work is just on going. Hope everything is going well and be finished soon. I will folk the project and fix issues if I found some.

**Comment by christianesperar** [comment]
Nice, just read his update today. I'm so excited on it.
