### ISSUE TITLE
how to bind a click event on iCheck checkbox?

### ISSUE THREAD

**Issue by xlkit456852** [puikinsh/gentelella#279]
I can't bind a click event on iCheck checkbox element ? Is there any idea ?

**Comment by SDKiller** [comment]
IMO, @puikinsh should get rid of `iCheck` script as it is not updated and supported for a long time and switch to pure css checkbox styling.

`iCheck` instead of standard events implements it's own which make maintaining js cumbersome if you deal with 3rd-party scrips which rely on 'normal' checkbox behavior.

It is not changed when checkboxes `checked` property was changed programmatically.
