### ISSUE TITLE
Discrepancy between NPM version and github repo

### ISSUE THREAD

**Issue by mkarajohn** [puikinsh/gentelella#285]
Currently in the version downloaded from NPM there are references to `url("../images/...)` from inside the file `node_modules/gentelella/build/css/custom.css` which produces errors during the build process. 

The [actual file](https://github.com/puikinsh/gentelella/blob/master/build/css/custom.css) in the repo currently does not have the problematic references.

**Comment by taraujoz** [comment]
I am having the same problem. I have installed gentelella with npm (to use in webpack), and included both custom.css and custom.js from the build directory, however it crashes due to the images dependencies in the CSS file. I would like to have the image folder in the build, since they are useful for starting a new project with this *amazing template* XD

Makes sense?

**Comment by mkarajohn** [comment]
@taraujoz to quote from [my other reply](https://github.com/puikinsh/gentelella/issues/283#issuecomment-250505456):

>The way I worked around it was to npm uninstall the gentelella package, manually add the entry "gentelella" : "git@github.com:puikinsh/gentelella.git" to package.json and then npm install again. This way it pulls from the repo, where the errors do not exist.

**Comment by taraujoz** [comment]
@mkarajohn it worked! Thank you!

**Comment by bravist** [comment]
Have same  problem
