### ISSUE TITLE
Implement 

### ISSUE THREAD

**Issue by nathansoaress** [puikinsh/gentelella#300]
how can I implement this in a Laravel project?

**Comment by AndreiCN** [comment]
Hi there @nathansoaress, unfortunately we can't cover every integration in every language however if you still have issues, you can check the Laravel website https://laravel.com and get from the documentation what you need to.

I hope this was helpful and you will succed, we will close this topic since it's an implementation issue and we can't handle all the scenarios out there.

Good look with it, we would also be glad to see it implemented in Laravel :)

Regards,
Andrew.
