### ISSUE TITLE
Smart wizard compatibility

### ISSUE THREAD

**Issue by lolingz02** [puikinsh/gentelella#335]
Hello!
im using this theme for quit a long time now and i dont have any issues with this theme. However when i decided to put the wizard inside a modal, im having this issue that every time i close the modal, i dont have any means of resetting the wizard.
smart wizard v3.3.1, which is currently used by gentellela, doesnt have the reset feature. There is an update now on smart wizard (v4.1.1 specifically) that has this feature and is already compatible with jquery v1.9+. The problem, however, is that i cannot plugin this version of smart wizard to this theme.
any way to fix it? thanks! any response would be greatly appreciated :)

**Comment by AndreiCN** [comment]
Hi there @lolingz02 ,

First of all we are glad that you're using our theme and about smart wizard plugin we're gonna try to integrate the latest version of it in our next update, if you have another question we're here for you :)

**Comment by lolingz02** [comment]
yey! It would be a great help if this would be fixed. Thank you so much!

**Comment by AndreiCN** [comment]
Hi again @lolingz02 ,

Now we understand what really happens there, well are two different plugins, what we use is Smart Wizard "refactored and extended" -  https://github.com/mstratman/jQuery-Smart-Wizard , and that's the latest version of it v3.3.1 and what you use is the original version of it - http://techlaboratory.net/smartwizard that is indeed v4.1.1 , so that's why you can't integrate it because it's another plugin :) 

So for some assistance , you can take a look here : https://github.com/mstratman/jQuery-Smart-Wizard , maybe your answer already exists in there. Hope it was helpful for you and for another questions you know where to find us :)

Regards,
Andrew.

**Comment by lolingz02** [comment]
oh, sorry bro. my bad. i thought they are the same plugins. just having this issue of resetting the wizard. i already posted this problem to their thread. hopefully they'll respond soon. thanks anyway. peace :D

**Comment by AndreiCN** [comment]
No worries, good luck !
