### ISSUE TITLE
device usage not working properly when testing responsiveness

### ISSUE THREAD

**Issue by Miss-Git** [puikinsh/gentelella#338]
When I was testing the responsiveness, the device usage element in the Dashboard didn't work well and even when I expanded page size to default of PC browsers, it still had problems. Would you fix it please?
----------------------------------
**EDIT 1:**
the related error is:
```
Uncaught TypeError: Cannot set property 'w' of undefined
    at m (jquery.flot.resize.js:22)
    at dispatch (jquery.min.js:4)
    at r.handle (jquery.min.js:4)
```

**Comment by AndreiCN** [comment]
Hi there @Miss-Git ,

Are you sure that you're using the right link ? https://colorlib.com/polygon/gentelella/index.html
If you do, can you please provide some screenshots to see exactly what happens there ? Will really help us to improve this even further. I'm saying that because on our side everything seems to work just fine.

Regards,
Andrew.
