### ISSUE TITLE
Space under dynamic table

### ISSUE THREAD

**Issue by xredpanda** [puikinsh/gentelella#367]
I am using one dynamic table, populated with some webservices. The issue is that there is a huge space between my table and footer.

Do you guys experience this?
![spaceaftertable](https://cloud.githubusercontent.com/assets/25173424/22017803/b1ceb642-dca3-11e6-8c17-b71d0a5074c7.png)

**Comment by AndreiCN** [comment]
Hi @xredpanda , 

That happens on dynamic tables only or in other pages to, i'm saying this because on my side it seems to behave just fine.

**Comment by LuisCamargoTI** [comment]
How do you solve this problem? I'm with the same problem! Thank's

**Comment by William-H-M** [comment]
Hi, I remember having this problem on one of my page, wasn't using DataTables as OP though, and seems to be a problem on th speed of the rendering so as a workaorund I just called again `init_sidebar()` again after I knew some elements where, the most important ones, loaded.

So this is just a workaround this seems to happen because `init_sidebar()` is called first than the other elements, in the case of DataTables the data is loaded first and the hided to do the pagination so maybe that's the reason.
