### ISSUE TITLE
Invalid CSS error DXImageTransf...

### ISSUE THREAD

**Issue by jedgalbraith** [puikinsh/gentelella#390]
After upgrading from `1.3.0` to `1.4.0` I'm getting an invalid CSS error when attempting to compile assets in Rails.

```
Sass::SyntaxError: Invalid CSS after "...x;filter:progid": expected ";", was ": DXImageTransf..."
gentelella/build/css/custom.min.css:1
```

**Comment by AndreiCN** [comment]
Hi there @jedgalbraith , 

You're getting that error because the code from SCSS file it was not written in SASS, it is in there just to prove the functionality between - SCSS - CSS - and minified CSS in the final using Gulp. Will take though into consideration a SASS version of it in the future, thank you !

**Comment by AlbertMulaki** [comment]
Thanks for the info!
