### ISSUE TITLE
Login CSS

### ISSUE THREAD

**Issue by merdj** [puikinsh/gentelella#438]
Hello,

This template is nice one, but, i observe something. when I try to use custom.css in login.html the scrollbar appears, but when I use custom.min.css it disappears.

Can anyone help me with this issue? I want to modify the custom.css, to remove the shadow in input box.

please help

thank you

**Comment by krzysiekpiasecki** [comment]
All templates includes statically  ```custom.min.css```, so you have to modify this css file or change link element to point ```custom.css``` - if you're not using a css preprocessor.

**Comment by merdj** [comment]
hi, trying to modify the custom.min.css is difficult and i tried to modify the custom.css and able to, unfortunately scrollbar appears. this is my problem.

**Comment by krzysiekpiasecki** [comment]
Use CSS preprocessor or just change html link element to point custom.css.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Orange network.                                                                                                                                                                                                                From: merdjSent: niedziela, 2 kwietnia 2017 12:40To: puikinsh/gentelellaReply To: puikinsh/gentelellaCc: Krzysztof Piasecki; CommentSubject: Re: [puikinsh/gentelella] Login CSS (#438)hi, trying to modify the custom.min.css is difficult and i tried to modify the custom.css and able to, unfortunately scrollbar appears. this is my problem.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/puikinsh/gentelella","title":"puikinsh/gentelella","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/puikinsh/gentelella"}},"updates":{"snippets":[{"icon":"PERSON","message":"@merdj in #438: hi, trying to modify the custom.min.css is difficult and i tried to modify the custom.css and able to, unfortunately scrollbar appears. this is my problem."}],"action":{"name":"View Issue","url":"https://github.com/puikinsh/gentelella/issues/438#issuecomment-290978198"}}}
