### ISSUE TITLE
build/images directory is missing after npm install

### ISSUE THREAD

**Issue by damianprzygodzki** [puikinsh/gentelella#444]
Morning everyone!

After `npm install --save gentelella` (@1.3.0) the `build/css/custom.min.css` is looking for a `/build/images/**` directory and some files. Here, on repository i can see it clearly, but in my `node_modules` is missing.

Did i something wrong?

**Comment by Driftersk** [comment]
Same here, images are missing. (@1.3.0)

**Comment by AndreiCN** [comment]
Thank you for pointing this out, we will take care of it in a future update.

**Comment by pdrosos** [comment]
@AndreiCN any news if this would be resolved soon? I have an error in webpack because of this and can not load the styles.
Thanks.

**Comment by AndreiCN** [comment]
@damianprzygodzki can you please provide a screenshot with your error ?

**Comment by pdeak** [comment]
I'm not @damianprzygodzki, but the issue is definitely happening. There's a number of errors produced, all roughly of the form:

```ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/gentelella/build/css/custom.css
Module not found: Error: Can't resolve '../images/forward_enabled_hover.png' in 'C:\Users\PDeak\Desktop\Sandbox\demos\oih-gui-prototype\node_modules\gentelella\build\css'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader?{"ident":"postcss"}!./~/gentelella/build/css/custom.css 6:24474-24520
 @ ./~/gentelella/build/css/custom.css
 @ multi ./~/bootstrap/dist/css/bootstrap.min.css ./~/gentelella/build/css/custom.css ./~/font-awesome/css/font-awesome.min.css ./src/styles.scss
```

I think the best screenshot to show the issue is really just this one:
![2017-07-13 12_39_56-build](https://user-images.githubusercontent.com/20069592/28164710-7f9e32f0-67c8-11e7-9ed6-0f7c409b869a.png)

That is what you get when you do an ```npm install gentelella```. The lack of an images folder in there, while the css/custom.css file clearly references things in ../images/* means it will never work as-is using bundlers such as Webpack.

**Comment by AndreiCN** [comment]
I see, interesting though when you get the package via download directly from git, images folder it is in there but indeed when you get it via npm it's ignored some how,  just for testing can you copy manually the folder images in build to see if the error still persisting ?

**Comment by pdeak** [comment]
If the images folder and related images are there then there are no problems.

**Comment by mdziekon** [comment]
That's probably because neither version ``1.3.0`` (which is currently delivered via npm) nor the latest stable tag ``1.4.0`` have ``build/images`` folder in the repository.

Could you please release a fix for that and tag it as ``1.4.1``? You could cherry-pick the commit that brought back the images directory (this is the one, I believe: https://github.com/puikinsh/gentelella/commit/eff4f55572554d0a793fc13be0dab28078ffdba7).

**Comment by readergirltracey** [comment]
is this fixed?

**Comment by AndreiCN** [comment]
Since npm version was updated to 1.4 images folder should be there, still get that error ? Especially @damianprzygodzki, if you have no further questions please close the ticket.
