### ISSUE TITLE
Fine uploader

### ISSUE THREAD

**Issue by brickcap** [puikinsh/gentelella#460]
Hi,

Thank you for creating this awesome template. 

Do you think it would be a good idea to include [fineuploader](https://fineuploader.com/)  for handling file uploads? Dropzone is great but fine uploader also has few other features that make it a very compelling choice:- like integration with form elements and direct uploads to s3. (Please check the feature comparison on their page) 

Thanks,
Akshat

**Comment by AndreiCN** [comment]
We will take this into consideration in a future update , thank you !

**Comment by rnicholus** [comment]
...and chunked uploads ;-)

**Comment by brickcap** [comment]
@rnicholus Yes Thank you!!

**Comment by AndreiCN** [comment]
Well @brickcap thank you again for your idea, we tried to bring this into it but it seems like it brings some problems in terms of compatibility so we will just postpone it since we have some another priorities for now so we will close this but we will certainly take it into consideration in the future !
