### ISSUE TITLE
Flash of blue body.

### ISSUE THREAD

**Issue by SamMousa** [puikinsh/gentelella#484]
Because the body has a blue background that is overlayed by a gray / white content when refreshing the page it shows a flash of blue, similar to a "flash of unstyled content".

**Comment by AndreiCN** [comment]
Hello,

To be honest I'm not quite sure what you mean, can you please provide a screenshot ?

**Comment by AndreiCN** [comment]
We're gonna close this ticket for now, but you can reopen it anytime :)

**Comment by SamMousa** [comment]
Oh, I missed your request for more info.

Are you familiar with the flash of unstyled content?  https://en.wikipedia.org/wiki/Flash_of_unstyled_content

Your template suffers from it due to the fact that the body has a different background color than the content div.

**Comment by AndreiCN** [comment]
Ah, I got it now. Ok I will investigate this and come with a solution, thank you for pointing this out !

**Comment by SamMousa** [comment]
So did you fix this? I see you closed it  but no commit mentions it?

**Comment by nkavian** [comment]
I've also seen this. Usually when the page has short content, the init_sidebar waits for the css/js files to load, and then init_sidebar adjusts the vertical position of the footer.

Sometimes when the page has long content, the footer can be seen about 10 pixels or more lower than the content body, and then the dark background is again visible.

Ideally, if the footer could be positioned using plain HTML instead of JS would solve this issue as well as my issue #499. Then with only additional CSS issue #498 can be solved..

**Comment by AndreiCN** [comment]
Well @SamMousa your issue was been solved yes, everything in this milestone that's closed means that was fixed if is not you'll get an explanation instead for sure. 

@nkavian both of your issues are in this milestone, if you noticed something else please open another issue to add it here ( this milestone ) :)

**Comment by kuait** [comment]
Hello @AndreiCN I'm using the django flavor and when I have short content a blue footer appears and there is other scenario that I posted here:  [https://stackoverflow.com/questions/46473264/blue-footer-in-gentelella-theme](gentelella-blue-footer) Thanks for the awesome work!
