### ISSUE TITLE
Footer alignment

### ISSUE THREAD

**Issue by nkavian** [puikinsh/gentelella#498]
Removing the `pull-right` from the footer causes the footer content to appear under the sidebar. Expected behavior is to display it to the right side of the sidebar.

**Comment by nkavian** [comment]
This is while using `footer_fixed`.

**Comment by AndreiCN** [comment]
Thank you for the suggestion @nkavian , we will take this into consideration. We will just close this issue for now but you can reopen it anytime if you need to :)

**Comment by nkavian** [comment]
Kindly, is the ticket closed because you have no intention to fix the bug or is this common practice and the bug will get fixed later anyways?

**Comment by AndreiCN** [comment]
No no, anything like that,  was closed because is not quite a bug, is more like a suggestion, but we will actually give this further investigation and if it will prove that's a better solution we will integrate in the next update.

We apologize for the inconvenience , every advice is awesome in order to make this product a better one :)

**Comment by nkavian** [comment]
Example of the issue: https://github.com/puikinsh/gentelella/compare/master...nkavian:truncated-footer?expand=1

**Comment by AndreiCN** [comment]
Hi again @nkavian ,

Well I've actually tested this issue you suggested but it seems that if I'm removing this "pull-right" class nothing happens and event it would we have a certain structure there but you can change it anytime as you wish if that doesn't fit to you , good luck !
