### ISSUE TITLE
Cropper buttons disfunction when $MENU_TOGGLE clicked

### ISSUE THREAD

**Issue by WhiteRavenProject** [puikinsh/gentelella#505]
Hello,

I am trying to implement a page where users can upload images to cropper and make it a profile photo after some cropping maybe. The problem is when $MENU_TOGGLE is clicked this buttons with fa starts to show nothing inside the button. I added a screen image. same with every browser.
![cropper](https://user-images.githubusercontent.com/10248736/27124323-66fbf5c4-50f9-11e7-94bf-bd3415568469.png)

**Comment by AndreiCN** [comment]
Do you have JS errors or something ?

**Comment by William-H-M** [comment]
@AndreiCN Hi I think I found the problem is on custom.css the culprit is this rule
```
.nav-sm .menu_section h3, .nav-sm .profile, .nav-sm span.fa {
	display: none;
}
```
The .nav-sm span.fa is takin those fa span as if they were being inside the menu

if I put a '.' at front will work, BUT will show the arrows on the menu

So I think the rule should be with a .side-menu as is the side menu the problem

I'll try to tested it out latter

**Comment by WhiteRavenProject** [comment]
ok i fixed it. thanks to @William-H-M .
what we need to do is change .nav-sm span.fa to .nav-sm .menu_section span.fa and it is done

**Comment by William-H-M** [comment]
@WhiteRavenProject Hi, looks like it's true, I'll do test on other page and if nothing looks wrong I will do a PR, thanks.

**Comment by AndreiCN** [comment]
Good job @William-H-M 👍
