### ISSUE TITLE
Datatable version 1.3.1

### ISSUE THREAD

**Issue by almayahi** [puikinsh/gentelella#527]
Hello 
Would it possible to update the Datatable to version 1.3.1?

**Comment by AndreiCN** [comment]
Hi,

Well it seems like the latest version is something like 1.10 already so when we will update it we will make sure that's the latest version and not something in the middle but not just yet because we have some other priorities to take care of for the moment.

P.S. Feel free to update it in your working version and also you can make a PR with it in order to make this product a better one, good luck !
