### ISSUE TITLE
Horizontal & Top navigation 

### ISSUE THREAD

**Issue by weedkiller** [puikinsh/gentelella#531]
Edited as this was just spam.

**Comment by William-H-M** [comment]
@cristianraiber shouldn't this be locked to avoid bad response? Because one thing is for ask for the layout anotther thing what he/her did.

**Comment by cristianraiber** [comment]
He/she wasn't asking for help. He/she just posted a few backlinks to their own admin panel, disguised as a ticket. Basically, the title didn't have anything to do with the links posted in the ticket, it was just plain spam :)

**Comment by weedkiller** [comment]
No I did not post to my own admin panel... I do not code admin panels, I have a valid purchase.

I posted a bitly link... so it would not show to the search engines unless someone clicked on the link! Grow up past the insecurity and help make a better product!

The point still remains - we need a **concise/cleaner top navigation to consolidate functional areas for the user**. This was raised several times even in the Themeforest comments as well & not just by me..

**Comment by William-H-M** [comment]
Hi, it's not about the fact that it's your admin panel/template is about the fact that, if not wrong because this was months ago, you just posted a link with nothing more, no description or exactly what have you tried or what should be good to be implemented.

For of horizontal navigation, it's something that the collaborators should decide on a future I guess.
