### ISSUE TITLE
overuse of !important

### ISSUE THREAD

**Issue by mpbunch** [puikinsh/gentelella#758]
custom.css / min.css
I understand wanting certain styles to always be a certain color, size, weight, etc.
However, using !important makes it so much more difficult to override the default theme.
Every time I pull a project down, and run npm install, I get vanilla gentelella which has !important all over it. If a client/product requires custom colors, sizes, weights, etc, the base gentelella css file has to be modified, or copied into a new file, altered and maintained. 

I'm not sure why !important needs to be used at all within the custom.css file.

**Comment by joshaabraham** [comment]
Hi, I am sorry to disturb you. I have no answer for you question. I an Stucked at the installation process. Is this theme usable on angular 6 ? whats your environnement ? asp.net mvc ? php ?  ... despite I've run the npm command, and tried to move some css closer to my pages, and components, and tried also to install the jquery , the bootstrap 3 and so ... I've finally admitted I was missing something important. Can you explain to me what you did during the process of installation, and into which environment you did it so that it works for you please ?

**Comment by mpbunch** [comment]
I am working with ReactJs
npm install gentelella

App.js
  import "../node_modules/gentelella/build/css/custom.min.css";

containers/Main.js
  import "./Main.css";

containers/Main.css
  .nav.navbar-nav>li>a{color:red !important}

Since custom.min.css has !important after the color the Main.css can not override the color, even with !important. 
  .nav.navbar-nav>li>a{color:#515356 !important}

**Comment by joshaabraham** [comment]
Thank you mpbunch ! Actually I am working with angular 6 , but I am also interested by reactJs (i've only whatched few videos). Have you tried angular 6 ? (i am not only speaking about genetelella, but in general). Would you prefer React to Angular in general ?  Would you say the error message are more meaningfull in ReactJs ? (Angular is hell about this, and there is no real justification to make distinction between Modules, services and components). I professionally suffer everyday haha :) (Angular has also made the color less accessible, I doubt the problem you lift up could be solved in angular).

**Comment by joshaabraham** [comment]
ok... this stuff is unusable. i got it. What a loss of time. probably the abandonned homework of a student . Impossible to get typings. and the package is two years old.

**Comment by mpbunch** [comment]
Unless the issue has been fixed, the issue should not be closed.

**Comment by mpbunch** [comment]
@AndreiCN  Has this issue been fixed? I still see !important all over the custom css file.
